### ISSUE TITLE
Server 2023 release missing from website, ltsc 2021 eol date not acknowledging IoT edition 

### ISSUE THREAD

**Issue by thecatontheceiling** [ChangeWindows/ChangeWindows#175]

**Comment by Studio384** [comment]
IoT edition is a desktop SKU, as such it is considered a part of the desktop timeline. However, for the 2021 release specifically, it deviates from desktops support life cycle and as such cannot be included in its timeline. I'll probably address that issue at some point. But for now, listing the desktop EOL date is more important than the IoT release date.

In regards to "Server 2023"; this is omitted because it doesn't exist. I'm assuming you're referring to Windows Server Annual Channel for Containers, but Microsoft hasn't shipped any version - preview or stable - of this product. As such, there is nothing to list. We presumably get something today, but that remains to be seen. Microsoft was going to provide more information after the original announcement, but as far as I'm aware that hasn't happened either.

**Comment by thecatontheceiling** [comment]
thank you for the quick response, I appreciate it a lot 👍

**Comment by Studio384** [comment]
23H2 ahs been added since the last comment.

**Comment by thecatontheceiling** [comment]
glad to see this project is being updated even if it doesnt have much traction
